# Generated by Django 5.2 on 2025-05-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProd', models.CharField(max_length=150)),
                ('precioProd', models.IntegerField()),
                ('fecha_creacion_prod', models.DateField()),
                ('descripcionProd', models.CharField(max_length=150)),
                ('imagenProd', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idMenu', models.AutoField(primary_key=True, serialize=False)),
                ('platoMenu', models.CharField(max_length=50)),
                ('descripcionMenu', models.CharField(max_length=150)),
                ('imagenMenu', models.CharField(max_length=255)),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.producto')),
            ],
        ),
    ]
