# Generated by Django 5.2 on 2025-05-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='precioMenu',
            field=models.IntegerField(null=True),
        ),
    ]
