# Generated by Django 5.2 on 2025-05-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_preciomenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='fk_producto',
        ),
    ]
